### ISSUE TITLE
BeerJS - #1

### ISSUE THREAD

**Issue by xtuc** [beerjs/strasbourg#1]
### Mercredi 07 septembre à 20 h

Pour ce premier BeerJS, je vous propose :
- The Dubliners (7 rue du Vieux Marché aux Poissons, 67000 Strasbourg)  
  ~~Mémé dans les orties (14 rue Munch, 67000 Strasbourg)~~

_Vous pouvez voter en dessous pour le bar que vous préférez._

**Comment by qtheuret** [comment]
Je ne connais pas Mémé dans les orties, mais The Dubliners, c'est un peu petit si on est plus de 7/8

**Comment by xtuc** [comment]
@qtheuret Oui, c'est aussi ce que je crains (pareil chez Mémé). Je peux toujours essayer de réserver à l'avance.
Si tu as une idée de bar dans le coin on est preneur :)

**Comment by qtheuret** [comment]
Je ne connais pas, mais peut-être du côté de la Place d'Austerlitz. Je sais qu'il y a pas mal de bar dans le coin.

**Comment by xtuc** [comment]
Le bar sera le `The Dubliners`.

**Comment by xtuc** [comment]
Nous sommes a l'intérieur :)
