### ISSUE TITLE
BeerJS - #2

### ISSUE THREAD

**Issue by xtuc** [beerjs/strasbourg#5]
Je vous propose une nouvelle édition du Beerjs. Voici le menu.

### JavaScript's optional chaining

![ddv1dx2xcaicig6](https://user-images.githubusercontent.com/1493671/27826483-7683e726-60b3-11e7-9369-73e7a70fc608.jpg)
(https://twitter.com/svensauleau/status/879738550882848768)

J'ai activement contribué à la réflexion et à l'implémentation de la spécification dans [Babel](https://github.com/babel/babel).

N'hésitez pas à ajouter les sujets que vous souhaitez aborder.

## Annoncement

L'événement aura lieu le mardi 25/7/2017 à partir de 19h et jusqu'à 21h.
Le bar selectionné est le [`Kelly's Síbín (see on schlouk-map)`](https://www.schlouk-map.com/places/kellys-sibin).

[Add to my calendar](http://www.google.com/calendar/event?action=TEMPLATE&dates=20170725T170000Z%2F20170725T190000Z&text=beerjs%20%235&location=Kelly's%20S%C3%ADb%C3%ADn%2C%204%20Rue%20du%20Vieux%20March%C3%A9%20aux%20Vins%2C%2067000%20Strasbourg%2C%20France&details=)

A très bientôt :rocket:

**Comment by quentin-sommer** [comment]
Super!
Dispo en juillet la semaine post 18h sauf le vendredi 21/07

**Comment by edi9999** [comment]
Perso, je suis plus dispo après le 15 Juillet, mais comme vous pouvez.

Le mieux serait le 13 ou le 14 Juillet pour moi

**Comment by DavidBabel** [comment]
As you want

**Comment by whollacsek** [comment]
Moi ça sera à partir du 17.

**Comment by xtuc** [comment]
L'événement aura lieu le mardi 25/7/2017 à partir de 19h et jusqu'à 21h.
Le bar selectionné est le [`Kelly's Síbín (see on schlouk-map)`](https://www.schlouk-map.com/places/kellys-sibin).

[Add to my calendar](http://www.google.com/calendar/event?action=TEMPLATE&dates=20170725T170000Z%2F20170725T190000Z&text=beerjs%20%235&location=Kelly's%20S%C3%ADb%C3%ADn%2C%204%20Rue%20du%20Vieux%20March%C3%A9%20aux%20Vins%2C%2067000%20Strasbourg%2C%20France&details=)

A très bientôt :rocket:

**Comment by whollacsek** [comment]
:)

Le lun. 17 juil. 2017 à 18:41, Sven SAULEAU <notifications@github.com> a
écrit :

**Comment by quentin-sommer** [comment]
@xtuc link seem broken https://www.schlouk-map.com/places/kellys-sibin

**Comment by xtuc** [comment]
@quentin-sommer yeah fixed, thanks.

**Comment by xtuc** [comment]
Merci aux participants, c'était cool!
